
services:
  web:
    image: nikola234/carshop-web:11-02-2025-23-31-89216-main
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/carDB
    depends_on:
      - mongo

  mongo:
    image: nikola234/carshop-web:11-02-2025-23-31-89216-main
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })' || exit 1"]
      interval: 10s
      retries: 10
      timeout: 10s


volumes:
  mongo_data:
