apiVersion: apps/v1
kind: Deployment
metadata:
  name: carshop-web
  namespace: carshop
  labels:
    app: carshop
    environment: production
    team: devops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: carshop
  template:
    metadata:
      labels:
        app: carshop
    spec:
      containers:
      - name: carshop-web
        image: nikola234/carshop-web:latest
        ports:
        - containerPort: 5000
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        envFrom:
        - configMapRef:
            name: carshop-config
        env:
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: carshop-secret
              key: app-root-username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: carshop-secret
              key: app-root-password
        - name: MONGO_URI
          valueFrom:
            configMapKeyRef:
              name: carshop-config
              key: MONGO_URI
#        livenessProbe:
#          httpGet:
#            path: /health
#            port: 5000
#          initialDelaySeconds: 60
#          periodSeconds: 15
#        readinessProbe:
#          httpGet:
#            path: /health
#            port: 5000
#          initialDelaySeconds: 40
#          periodSeconds: 10
        volumeMounts:
        - mountPath: "/app/data"
          name: app-storage
      volumes:
      - name: app-storage
        persistentVolumeClaim:
          claimName: app-pvc
