apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
  namespace: carshop
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
