name: Build and Push Docker Image

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Build Version
        id: versioning
        run: |
          DATE=$(date +%d-%m-%Y-%H-%M)
          SHORT_SHA=${GITHUB_SHA::5}
          BRANCH=$(echo "${GITHUB_REF##*/}" | tr '/' '-')
          VERSION="${DATE}-${SHORT_SHA}-${BRANCH}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Generated Version: $VERSION"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t nikola234/carshop-web:${{ env.VERSION }} .

      - name: Push Docker Image
        run: docker push nikola234/carshop-web:${{ env.VERSION }}
      
      - name: Checkout main branch
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git fetch origin main
          git checkout main


      - name: Update Kubernetes and Docker Compose with New Image Version
        run: |
          sed -i "s|image: .*|image: ${{secrets.DOCKERHUB_USERNAME}}/carshop-web:${{ env.VERSION }}|" kubernetes/car_deployment.yaml
          sed -i '0,/image: .*/s|image: .*|image: ${{secrets.DOCKERHUB_USERNAME}}/carshop-web:${{ env.VERSION }}|' docker-compose.yml
          
            
          git add kubernetes/car_deployment.yaml
          git add docker-compose.yml
            
          git commit -m "Updated image version to: ${{ env.VERSION }}"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

            sleep 10

      - name: Notify on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
              server_address: smtp.gmail.com
              server_port: 587
              username: ${{ secrets.SEND_EMAIL }}
              password: ${{ secrets.SEND_PASSWORD }}
              subject: "Build Success"
              body: "Build and push succeeded for version ${{ github.run_number }}!"
              to: ${{ secrets.RECEIVE_EMAIL }}
              from: ${{ secrets.SEND_EMAIL }}
    
      - name: Notify on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
              server_address: smtp.gmail.com
              server_port: 587
              username: ${{ secrets.SEND_EMAIL }}
              password: ${{ secrets.SEND_PASSWORD }}
              subject: "Build Failure"
              body: "Build and push failed for version ${{ github.run_number }}!"
              to: ${{ secrets.RECEIVE_EMAIL }}
              from: ${{ secrets.SEND_EMAIL }}
